### PR TITLE
Detector-Competition-Fix: Fix/Remove baseapi detector (no longer exists)

### PR DESCRIPTION
**Pull request by lc**
### Description:
The `baseapiio` detector & verifier is no longer needed as the API has been removed/deleted:

image

Visiting `https://api.base-api.io/v1/forms?page=1&per_page=10` you get redirected:

image

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

**Comment by ahrav** [comment]
Thanks a lot for the contribution @lc. Would you mind also deleting the detector from the [defaults.go](https://github.com/trufflesecurity/trufflehog/blob/2189dc9b0f9a0e59b40d0032d314c7e439ea1a1d/pkg/engine/defaults.go#L1254-L1254) list.

**Review by ahrav — APPROVED** [review]
Looks like some compilation failures due to the missing file. We can just remove the detector from the defaults list.

**Comment by lc** [comment]
Whoops totally forgot about the `defaults.go` - Fixed! @ahrav

**Comment by ahrav** [comment]
Whooops totally forgot to wait for defaults.go to get updated 🤣 🤦 [PR](https://github.com/trufflesecurity/trufflehog/pull/1993) should fix it.

**Comment by lc** [comment]
That was my bad @ahrav – I had fixed it locally & pushed...Didn't look at the output and see that the push failed lol

CleanShot 2023-10-25 at 09 23 10

**Comment by ahrav** [comment]
> That was my bad @ahrav – I had fixed it locally & pushed...Didn't look at the output and see that the push failed lol
> 
> 
> 
> CleanShot 2023-10-25 at 09 23 10
> 
> 

No worries at all, I've done the same thing more times than I can count. I'm gonna chalk it up to haven't had my coffee yet this AM. ☕

**Pull request merged**
