### PR TITLE
Update github action to support generic cli command input

### PR DESCRIPTION
**Pull request by jwenz723**
This PR partially resolves https://github.com/trufflesecurity/trufflehog/issues/540. Specifically the portion of https://github.com/trufflesecurity/trufflehog/issues/540 regarding adding support for all trufflehog input arguments.

This is one possible way which can generically support passing in all of the available commands and arguments available for the trufflehog cli.

### CODE REVIEW

**Comment by jwenz723** [comment]
Note that since declaring expressions in default values for github actions inputs isn't supported I have simplified the default command to `git file://./` which is slightly different than the default command as it currently exists in branch `main` where it is required that the caller of the action specify `inputs.path` and `inputs.base`.

**Comment by dustin-decker** [comment]
This is great, thank you! Unfortunately it's a breaking change at the moment. In retrospect we probably should have versioned the GitHub action separately... 

What if we preserved the current inputs and arguments and expanded the `cli_cmd` args separately after those?

**Comment by jwenz723** [comment]
@dustin-decker I've made the change as you suggested. I was able to validate this in my open github actions workflow using the step:

```yaml
      - name: TruffleHog OSS
        uses: jwenz723/trufflehog@f72ed383cee5994b1c430b5ded1bef6243f8c3eb
        with:
          path: "./"
          base: ${{ github.base_ref }}
          head: ${{ github.head_ref }}
          extra_args: --only-verified
```

I have `jwenz723/trufflehog@f72ed383cee5994b1c430b5ded1bef6243f8c3eb` because in that particular version of the action it makes use of [a docker image which I pushed into my own registry](https://hub.docker.com/layers/trufflehog/jwenz723/trufflehog/latest/images/sha256-3c58e615fdf922c282c265e42e89fc44b6c3989b58f43ad54663f2909d8a5612?context=explore) so that I could test with the entrypoint.sh script compiled into the image.

**Review by bill-rich — APPROVED** [review]
Looks good. Thanks @jwenz723 for the contribution!

**Pull request merged**
