### PR TITLE
Add MacPorts installation instructions

### PR DESCRIPTION
**Pull request by herbygillot**
https://ports.macports.org/port/trufflehog/

### CODE REVIEW

**Comment by dustin-decker** [comment]
Who maintains this package? We've only published packages to the readme that we maintain.

**Comment by herbygillot** [comment]
> Who maintains this package? We've only published packages to the readme that we maintain.

In MacPorts, a maintainer volunteers to maintain a port for a piece of software.  A port is defined by its `Portfile`. Here's the one for `trufflehog`: https://github.com/macports/macports-ports/blob/master/security/trufflehog/Portfile So currently the maintainer is myself.

**Comment by dustin-decker** [comment]
We appreciate you maintaining that but do not want to post 3rd party maintained packages. Our homebrew package is automatically updated by us. Thank you for your contribution though!

**Comment by herbygillot** [comment]
Understood. Thanks.

**Pull request closed without merging**
