### PR TITLE
Added gtmetrix scanner

### PR DESCRIPTION
**Pull request by roxanne-tampus**

### CODE REVIEW

**Review by dustin-decker — CHANGES_REQUESTED** [review]
Hey Roxanne, the product name is `gtmetrix` but you have `gtmetrics`. Can you rename everything to match that?

**Comment by roxanne-tampus** [comment]
My apologies. I just created a PR for this. Thanks!

**Comment by dustin-decker** [comment]
Thank you! I'll close this one then

**Comment by dustin-decker** [comment]
Reopened because I misunderstood. Merged the PR for the proto change.

**Comment by roxanne-tampus** [comment]
Apologies. I only read the closing part so I added a new PR for this. Didn't know it is reopened. Let me just close this PR. Thanks!

**Pull request closed without merging**
