### PR TITLE
[chore] - Update Chunk struct comment

### PR DESCRIPTION
**Pull request by ahrav**
…ering

### Description:
Update the comment of the `Chunk` struct to inform users the ordering of the fields are significant and have memory implications.

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

**Comment by rgmz** [comment]
If you want to be paranoid, you could hard-code a compile time check that will panic if the size fails.

**Review by rosecodym — APPROVED** [review]
❤️

**Comment by rosecodym** [comment]
> If you want to be paranoid, you could hard-code a compile time check that will panic if the size changes.

I think @ahrav thought you were joking, but...I kinda like this? [It doesn't look too weird.](https://commaok.xyz/post/compile-time-assertions/)

**Comment by ahrav** [comment]
what about a test as well? Something like:
```
// TestChunkSize ensures that the Chunk struct does not exceed 80 bytes.
func TestChunkSize(t *testing.T) {
	assert.Equal(t, unsafe.Sizeof(Chunk{}), uintptr(80), "Chunk struct size exceeds 80 bytes")
}
```

**Comment by ahrav** [comment]
> If you want to be paranoid, you could hard-code a compile time check that will panic if the size changes.

Is there an easy way to do this without having to import C as in the example Cody mentioned?

**Comment by rgmz** [comment]
Oh my. I was naively thinking there was a way to evaluate expressions at compile-time. I think I confused it with `go generate` or runtime init panics (e.g., placing it inside `init {}`).

Go makes me sad.

**Comment by ahrav** [comment]
> Oh my. I was naively thinking there was a way to evaluate expressions at compile-time. I think I confused it with `go generate` or runtime init panics (e.g., placing it inside `init {}`).
> 
> Go makes me sad.
> 
> > oooo maybe something cute like:
> 
> This is both amazing and terrifying.

Hahaha, this was fun, but I might just let the test catch changes 🤣

**Review by dustin-decker — APPROVED** [review]

**Pull request merged**
