### PR TITLE
Resolve #1167 by adding support for the AWS_SESSION_TOKEN 

### LINKED ISSUE #1167: AWS_SESSION_TOKEN ignored
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

Docker image `trufflesecurity/trufflehog:3.29.0`

### Trace Output

```
2023-03-10T18:35:20Z    info-2  trufflehog      trufflehog 3.29.0
2023-03-10T18:35:20Z    info-2  trufflehog      engine started  {"workers": 16}
2023-03-10T18:35:20Z    info-2  trufflehog      loaded decoders {"count": 2}
2023-03-10T18:35:20Z    info-2  trufflehog      loaded detectors        {"total": 728, "verification_enabled": 728, "verification_disabled": 0}
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷

2023-03-10T18:35:20Z    info-0  trufflehog      Scanning bucket {"source_type": "SOURCE_TYPE_S3", "source_name": "s3", "bucket": "xxx"}
2023-03-10T18:35:21Z    error   trufflehog      could not list objects in s3 bucket     {"source_type": "SOURCE_TYPE_S3", "source_name": "s3", "bucket": "xxx", "error": "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\n\tstatus code: 403, request id: xxx, host id: xxx"}
2023-03-10T18:35:21Z    info-0  trufflehog      Scanning bucket {"source_type": "SOURCE_TYPE_S3", "source_name": "s3", "bucket": "xxx"}
2023-03-10T18:35:21Z    error   trufflehog      could not list objects in s3 bucket     {"source_type": "SOURCE_TYPE_S3", "source_name": "s3", "bucket": "xxx", "error": "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\n\tstatus code: 403, request id: xxx, host id: xxx/xxx="}
2023-03-10T18:35:22Z    info-2  trufflehog      finished scanning       {"chunks": 0, "bytes": 0}
```

### Expected Behavior

Truffle Hog can be run using temporary credentials defined by an AWS access key id + secret key + session token.

### Actual Behavior

Failure to authenticate with AWS before scanning a bucket:

`The AWS Access Key Id you provided does not exist in our records.`

### Steps to Reproduce

1. Run `aws sts get-session-token` to output a json object with the three required environment variable values
2. Save the below script
3. Modify the script to use the values from `aws sts-get-session-token`
4. Run the script. Observe that the `aws s3 ls` command succeeds, but the truffle hog command fails with `The AWS Access Key Id you provided does not exist in our records.`
```
#!/bin/bash

set -e

aws_access_key_id=foo
aws_secret_access_key=bar
aws_session_token=qux

echo $aws_access_key_id

docker run \
    --rm \
    -e AWS_ACCESS_KEY_ID=$aws_access_key_id \
    -e AWS_SECRET_ACCESS_KEY=$aws_secret_access_key \
    -e AWS_SESSION_TOKEN=$aws_session_token \
    -u 10000:10000 \
    amazon/aws-cli \
    s3 ls

docker run \
    --rm \
    -e AWS_ACCESS_KEY_ID=$aws_access_key_id \
    -e AWS_SECRET_ACCESS_KEY=$aws_secret_access_key \
    -e AWS_SESSION_TOKEN=$aws_session_token \
    -u 10000:10000 \
    ghcr.io/trufflesecurity/trufflehog:3.29.0 \
    s3 --bucket=some-non-public-bucket --no-update
```

## Environment
 * OS: Docker host is Ubuntu 22.04 LTS
 * Docker version 20.10.12, build 20.10.12-0ubuntu4

## Additional Context
None

### References

None

### PR DESCRIPTION
**Pull request by iamjpotts**
This is a fix for #1167.

Edited to add:

This change is submitted on behalf of my employer, `El Toro.com, LLC` and I have internal written approval to do so.

### CODE REVIEW

**Review by dustin-decker — APPROVED** [review]
Thank you for the contribution!

**Comment by dustin-decker** [comment]
@iamjpotts can you sign the CLA please? We won't be able to accept the contribution until you do.

**Comment by iamjpotts** [comment]
@dustin-decker thanks for your interest in my contribution.

The CLA is in review and I should have feedback in 1-2 weeks on it.

**Comment by iamjpotts** [comment]
@dustin-decker 

I'm trying to figure out the mechanics/process for a corporate entity to sign the CLA. For individuals, it's obvious - click the grey/yellow button above and follow thru with the electronic acceptance.

What's the mechanics/process for a corporate entity?

**Comment by dustin-decker** [comment]
@iamjpotts it should be the same process, that CLA covers individuals on behalf of a company too. See point 4)

>>>You represent that you are legally entitled to grant the above license. If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer, that your employer has waived such rights for your Contributions to the Company, or that your employer has executed a separate Corporate CLA with the Company.

**Comment by iamjpotts** [comment]
@dustin-decker 

Thanks for the response.

By `same process` - do you mean that only my account `iamjpotts` needs to sign the CLA in the scenario where the PR has IP from my employer (which is the case with this PR)? No other signatures required, such as by an executive officer of the company?

**Comment by dustin-decker** [comment]
That's correct @iamjpotts, as long as you have received permission to make contributions on behalf of your employer and they have waived their rights to your contributions, the standard CLA signed by your GitHub user covers it. This is the relevant attestation from point 4:

>you represent that you have received permission to make Contributions on behalf of that employer, that your employer has waived such rights for your Contributions to the Company

**Comment by iamjpotts** [comment]
I have received written permission to make this contribution on behalf of my employer, `El Toro.com, LLC`.

**Pull request merged**
