### PR TITLE
[bug] - fix shodan detector

### PR DESCRIPTION
**Pull request by ahrav**
Screenshot 2023-07-29 at 9 43 07 PM

### CODE REVIEW

**Comment by mcastorina** [comment]
If you're up for it, we could add indeterminacy fixes too.

**Comment by rosecodym** [comment]
yeah i'd love for someone other than me to go through the process and see how it feels

**Comment by ahrav** [comment]
> If you're up for it, we could add indeterminacy fixes too.

I'll add the indeterminacy in a separate PR as I probably won't get to it until this Friday during hack time. I was hoping to get this out before then given we have a handful of individuals that have mentioned this detector isn't working correctly.

**Review by rosecodym — APPROVED** [review]
what's the problem that this solves?

**Pull request merged**
