### PR TITLE
fix: added correct api endpoint for verification & logic for Aeroworkflow

### LINKED ISSUE #3434: Issue with correct endpoint & pattern detection in AeroWorkFlow
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### Expected Behavior

Correct API endpoint for verification must be used `/api/{accountid}/me` which aligns with other detector patterns as well.

Reference: https://api.aeroworkflow.com/swagger/index.html

### Actual Behavior
Currently the API for endpoint verification is `/api/{accountid}/v1/AeroAppointments`. This endpoint is not appropriate as it might involve COGs.

### Expected Behavior
The current API key pattern should match the pattern required.

### Actual Behavior
The` \b` at the end of the regex is looking for a word boundary. In this case, the 20-character sequence is immediately followed by a `/`, which is not a word character. The word boundary `\b` is expecting a transition from a word character to a non-word character or the end of the string, which doesn't occur here.

## Environment
 * OS: [e.g. iOS]
 * Version [e.g. 22]

### References

* #0000

### PR DESCRIPTION
**Pull request by sahil9001**
### Description:
Fixes #3434 .

API Endpoint Correction:
   - Current: The detector uses `/api/{accountid}/v1/AeroAppointments` for verification.
   - Issue: This endpoint is not appropriate as it might involve COGs.
   - Fix: Update to use `/api/{accountid}/me`, which aligns with other detector patterns.
   - Reference: https://api.aeroworkflow.com/swagger/index.html

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

**Comment by sahil9001** [comment]
@rgmz

**Comment by zricethezav** [comment]
> Issue: This endpoint is not appropriate as it might involve COGs.

Can you elaborate on this? I'm not familiar with COGs

**Comment by sahil9001** [comment]
> > Issue: This endpoint is not appropriate as it might involve COGs.
> 
> Can you elaborate on this? I'm not familiar with COGs

In this scenario, "COGs" is referring to sensitive or privileged information related to customer-owned items or data. The concern seems to be that the current endpoint (`/api/{accountid}/v1/AeroAppointments`) might be accessing or exposing information about customer-owned goods or property, which could be a privacy or security issue.
By switching to the `/api/{accountid}/me` endpoint, the system would likely be accessing only user-specific information rather than potentially sensitive customer-owned data. This change aligns better with standard practices for user verification and reduces the risk of inappropriately handling customer-owned information.

**Review by zricethezav — APPROVED** [review]
fixes the regex, approved.

**Pull request merged**
