### PR TITLE
Detector-Competition-Fix: Fix/Deprecate Prospect.io

### PR DESCRIPTION
**Pull request by lc**
### Description:
https://api.prospect.io no longer exists and has been shutdown. This PR removes the detector, updates the protobufs, and removes it from defaults.go

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

**Review by zricethezav — APPROVED** [review]
@lc lgtm, just needs a conflict resolve

**Comment by lc** [comment]
Fixed @zricethezav

**Comment by lc** [comment]
aaaand updated protos again

**Comment by zricethezav** [comment]
> aaaand updated protos again

😬 thanks

**Pull request merged**
