### PR TITLE
Add GitLab CI Pipeline Example in Documentation

### PR DESCRIPTION
**Pull request by RoseSecurity**
### Description:

> [!IMPORTANT]
> This PR addresses [this Issue](https://github.com/trufflesecurity/trufflehog/issues/2600) to add documentation for running TruffleHog in GitLab CI pipelines

This pull request aims to enhance the project's documentation by adding instructions on integrating TruffleHog into GitLab CI pipelines. With this documentation update, our team and future contributors will have clear guidance on how to set up and configure TruffleHog within GitLab CI workflows, thereby bolstering our security practices.

### Checklist:

* [X] Tests passing
* [X] Lint passing

### CODE REVIEW

**Review by ahrav — APPROVED** [review]
This is really helpful. Thanks a lot for the contribution @RoseSecurity

**Comment by RoseSecurity** [comment]
Thank you for your prompt review!

I greatly appreciate the work you all do. This tool has been immensely beneficial to me, and I'm happy to have had the opportunity to contribute.

**Comment by ahrav** [comment]
> Thank you for your prompt review!
> 
> I greatly appreciate the work you all do. This tool has been immensely beneficial to me, and I'm happy to have had the opportunity to contribute.

Thank you for the kind words, as well as being a part of the community. We really appreciate it ❤️

**Comment by MattKeeley** [comment]
@RoseSecurity with gitlab, is it possible to have trufflehog only scan the changed files in the pipeline? With monorepos for example, scanning the whole path isnt feasible.

**Comment by RoseSecurity** [comment]
> @RoseSecurity with gitlab, is it possible to have trufflehog only scan the changed files in the pipeline? With monorepos for example, scanning the whole path isnt feasible.

I may need to do some additional testing on this to understand GitLab's fetching policy. I attempted to use the `trufflehog git file://. --since-commit HEAD`, it failed due to not having the appropriate git information. I will investigate this further

**Comment by MattKeeley** [comment]
Ended up getting this to work on just changed introduced by devs. Thanks!

**Pull request merged**
