### PR TITLE
[feat] - Add Detector Description to JSON output

### LINKED ISSUE #3380: Expose Detector Description in JSON output
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

## Description
Expose the new Description field via the JSON output.

### Preferred Solution
```
{
...
"DetectorName": "OpenAI",
"Description": "OpenAI provides various AI models and services. The API keys can be used to access and interact with these models and services.",
...
}
```

### PR DESCRIPTION
**Pull request by ahrav**
### Description:
This PR includes the Detector Description in the output.

Screenshot 2024-10-12 at 9 29 23 PM

Addresses: https://github.com/trufflesecurity/trufflehog/issues/3380
### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

**Review by kashifkhan0771 — APPROVED** [review]
This looks like a good approach to me.
Just a QQ: If we detect more than one secret for a single detector, will this logic print description for each result even the detector is same?

**Review by abmussani — APPROVED** [review]
Looks good to me.

**Comment by abmussani** [comment]
> This looks like a good approach to me. Just a QQ: If we detect more than one secret for a single detector, will this logic print description for each result even the detector is same?

I believe, Yes.  Output includes Detector information per identified credentials.

**Comment by ahrav** [comment]
> > This looks like a good approach to me. Just a QQ: If we detect more than one secret for a single detector, will this logic print description for each result even the detector is same?
> 
> I believe, Yes. Output includes Detector information per identified credentials.

Good question. The description is printed for **each result**. In the `detectChunk` method, we call `e.processResult` on each result returned by the detector [as seen here](https://github.com/trufflesecurity/trufflehog/blob/cf54b71a9410df1960bad536b227958e776ace71/pkg/engine/engine.go#L1096-L1098). During `processResult`, the description is added once the detector result is converted to a `ResultWithMetadata`. So, unless the result is deduplicated later, the description will be applied to every result [as shown here](https://github.com/trufflesecurity/trufflehog/blob/cf54b71a9410df1960bad536b227958e776ace71/pkg/engine/engine.go#L1195-L1199).

**Comment by kashifkhan0771** [comment]
@abmussani  I guess that is something we can note down for future if possible. Grouping same detector results and showing description once for each detector.

@zricethezav @nabeelalam ⬆️

**Review by kashifkhan0771 — APPROVED** [review]

**Review by CameronLonsdale — APPROVED** [review]

**Pull request merged**
