### PR TITLE
continue scanning on detector / decoder panic

### PR DESCRIPTION
**Pull request by dustin-decker**

### CODE REVIEW

**Review by mcastorina — APPROVED** [review]
This means a worker will stop without restarting, which means if all workers panic we could be left with no goroutines scanning chunks.

Probably not a huge concern right now.

**Comment by dustin-decker** [comment]
That's a good point, we can improve that.

**Comment by zricethezav** [comment]
@mcastorina @dustin-decker should this PR be closed or do we still want to introduce this change?

**Comment by mcastorina** [comment]
I think we can merge it and create a separate ticket for monitoring the number of workers we have.

**Pull request merged**
