### PR TITLE
Added support for ignoring specific file and path patterns with .fileignore

### PR DESCRIPTION
**Pull request by ryanohoro**
Implements #8 

Uses fnmatch to selectively ignore commit blobs with specific file paths. Uses the "a" side diff path name. No default entries.

Adding patterns to .fileignore:

```
# Use UNIX style pattern matching to select files for truffleHog to ignore. Use slashes for directory matching.
# Examples:
# *.md
# LICENSE
# temp/*
```

### CODE REVIEW

**Comment by gbrayut** [comment]
I am getting some strange results with File: None

Example: from this merge https://github.com/bosun-monitor/bosun/pull/1598

```
File: None
Date: 2016-02-16 10:10:37
Branch: master
Commit: cmd/bosun: Add over, shift, and merge funcs

This adds the ability to graph multiple seriesSets in expression graphs, and also graph things like week-over-week. Fixes #985

@@ -0,0 +1,1967 @@
+// Copyright (c) 2012-2015 Ugorji Nwoke. All rights reserved.
+// Use of this source code is governed by a MIT license found in the LICENSE file.
+
+package codec
+
```
The Ugori files are from bosun/vendor/github.com/ugorji/go/codec/ and don't exist in that commit.

Also you might want to add the commit hash to the header block, as tracking by date/commit message can be difficult.

**Comment by ryanohoro** [comment]
Yeah, some diffs have no a_path/b_path value. It might be because there's no previous or next commit when the diff is generated. All output is the result of comparing two commits, not looking at the commits themselves. Adding a new PR to try to minimize when File: None appears.

**Comment by ryanohoro** [comment]
We can address the header block more in another issue if you want to create one as a feature request.

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this PR.

**Pull request closed without merging**
