### PR TITLE
Add RawV2 Results to the JSON Output

### PR DESCRIPTION
**Pull request by yilmi**
@ahrav did work on adding a RawV2 field in the Result struct to permit the collection of multipart secrets. This work was completed in #710 last year.

While the current implementation collects RawV2 for a lot of detector types, this value is never passed to the JSON Result output.

This PR changes this behavior:
- Adding the RawV2 values to the JSON output
- Handling RawV2 for the Azure, Datadog and GCP detectors

### CODE REVIEW

**Comment by dustin-decker** [comment]
Thanks @yilmi. Could you pull the latest from main? There is a conflict with #1271 which was recently merged and added RawV2 to GCP, but using the cleaned marshaled json.

**Comment by yilmi** [comment]
> Thanks @yilmi. Could you pull the latest from main? There is a conflict with #1271 which was recently merged and added RawV2 to GCP, but using the cleaned marshaled json.

@dustin-decker done, I saw the other PR and was waiting for your input, I removed my changes so the GCP detector shouldn't be affected by this PR now. Let me know if there's anything else, thanks!

**Review by dustin-decker — APPROVED** [review]
Looks good, thanks @yilmi!

**Comment by ahrav** [comment]
> Thanks @dustin-decker, I don't want to push it but do you think you folks could release this change along with the rest of @ahrav work on the utf-8 and base64 decoders? We have our scheduled scan running on Friday evenings, I'd like to consume the latest changes to get all the nice changes from v3.32.0 and this. If not that's ok, I can also wait ;-)

just tagged [v3.32.1](https://github.com/trufflesecurity/trufflehog/releases/tag/v3.32.1)

**Pull request merged**
