### PR TITLE
added cody gateway token detection code

### PR DESCRIPTION
**Pull request by shivasurya**
### Description:
Detect Sourcegraph Cody Gateway API Token and verify using cody gateway endpoint

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

**Comment by shivasurya** [comment]
I have opened an issue [here](https://github.com/trufflesecurity/trufflehog/issues/1884) for detailed info. If you're looking to test/any question, please let me know. Thanks

**Comment by zricethezav** [comment]
Thanks for the PR @shivasurya! Did you follow the [testing guidelines](https://github.com/trufflesecurity/trufflehog/blob/main/hack/docs/Adding_Detectors_external.md#testing-the-detector)? and could you supply a screenshot of the test passing locally? Thanks!

**Comment by shivasurya** [comment]
Hi @zricethezav 
Thanks for reviewing. I have tested locally and resolved the conflict.

Screenshot 2023-10-11 at 2 25 05 PM

If you would like to test, let me know - I can get you trial cody gateway token. Can you reach out security at sourcegraph. Thanks.

**Comment by bugbaba** [comment]
Hi @shivasurya,

I couldn't find the API documentation for the sourcegraph Cody, Could you please guide me on where you got the `/v1/limits` endpoint from? what other endpoints can be accessed using the token and does it work with the [Sourcegraph GraphQL API](https://docs.sourcegraph.com/api/graphql)?

**Comment by shivasurya** [comment]
Thanks @zricethezav , I have responded in Discord chat with trial keys

**Review by zricethezav — APPROVED** [review]

**Pull request merged**
