### PR TITLE
fix: added correct verification endpoint and logic for apiscience

### LINKED ISSUE #3441: Issue with verification endpoint for apiscience
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

### Expected Behavior
As the company has been acquired by APImetics, corresponding API endpoints shall be used instead of APIScience ones.
Reference: https://apicontext.com/apimetrics-expands-purchase-api-science/
Reference: https://docs.apimetrics.io/reference/list-all-calls

### Actual Behavior
The detector breaks as the endpoint is invalid. 

## Environment
 * OS: [e.g. iOS]
 * Version [e.g. 22]

### References

* #0000

### PR DESCRIPTION
**Pull request by sahil9001**
### Description:
Fixes #3441 , screenshot for test results:

Screenshot 2024-10-17 at 3 22 13 AM

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

**Comment by sahil9001** [comment]
@rgmz @zricethezav

**Comment by zricethezav** [comment]
@sahil9001 in this case I think it would make more sense to deprecate this detector and create a new one for `apimetrics`

**Comment by sahil9001** [comment]
Is there a command for deprecating detector?

**Comment by zricethezav** [comment]
@sahil9001 nope but you can follow this PR https://github.com/trufflesecurity/trufflehog/pull/2856 as an example

**Comment by sahil9001** [comment]
Done @zricethezav , please have a look at this #3475

**Comment by kashifkhan0771** [comment]
Closing this PR as another PR is created for these changes: https://github.com/trufflesecurity/trufflehog/pull/3475

**Pull request closed without merging**
