### PR TITLE
fixing databricks detector for azure workspaces

### PR DESCRIPTION
**Pull request by 4390c336**
### Description:
the regex needed updating to match the azure workspace domain used for databricks. and the PAT was also not detecting tokens ending with -\d
Screenshot 2024-07-02 at 19 24 53

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

**Review by ankushgoel27 — COMMENTED** [review]
i tested the keypat regex change and the old one doesn't work properly. the new regex seems to detect the token properly including the -\d

**Comment by ankushgoel27** [comment]
([a-z0-9-]+(?:\.[a-z0-9-]+)*\.(cloud\.databricks\.com|gcp\.databricks\.com|azuredatabricks\.net|amazonaws\.com))

can you please add the amazon to the regex? databricks also generate workspaces on amazon aws

**Comment by hamza-db** [comment]
@ankushgoel27 I can't find that domain for Azure anywhere. Can you point out any examples from a repo or documentation or any other source?

**Comment by 4390c336** [comment]
I can't find that domain for Azure anywhere. Can you point out any examples from a repo or documentation or any other source?

**Comment by ankushgoel27** [comment]
> I can't find that domain for Azure anywhere. Can you point out any examples from a repo or documentation or any other source?

my apologies, this is not the format for AWS databricks domain. please disregard my last comment.

**Comment by zricethezav** [comment]
@4390c336 can you provide any supporting documentation for this change?

**Comment by 4390c336** [comment]
@zricethezav 
you can find it here : https://learn.microsoft.com/en-us/azure/databricks/release-notes/product/2020/april#unique-urls-for-each-azure-databricks-workspace

**Comment by 4390c336** [comment]
@zricethezav is there anything else I need to work on ?

**Review by ahrav — APPROVED** [review]
Thanks for updating this @4390c336, we really appreciate it.

**Pull request merged**
