### PR TITLE
[chore] -  Record metrics before reset

### PR DESCRIPTION
**Pull request by ahrav**
### Description:
Explain the purpose of the PR.

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

**Comment by rosecodym** [comment]
What's the reason for this change?

**Comment by ahrav** [comment]
> What's the reason for this change?

Our metrics were reporting some checkout durations that were very very large due to integer overflow for newly created buffers with the zero value for time.Time. This was then resulting in metrics that were incorrect.

**Review by rosecodym — APPROVED** [review]
ah, ok. this isn't necessary but you might also consider modifying `recordBufferReturn` to take the buffer itself as a parameter and then call `buf.RecordMetric()` inside of it. then all the buffer return metrics will be in one place.

**Comment by ahrav** [comment]
> ah, ok. this isn't necessary but you might also consider modifying `recordBufferReturn` to take the buffer itself as a parameter and then call `buf.RecordMetric()` inside of it. then all the buffer return metrics will be in one place.

Yea, I like that idea thanks.

**Pull request merged**
