### PR TITLE
Check private keys concurrently

### PR DESCRIPTION
**Pull request by rgmz**
### Description:
This uses a [WaitGroup](https://pkg.go.dev/sync#WaitGroup) to look up private keys concurrently, rather than in sequence.

~Edit: I somehow forgot to make the actual functions go routines. I will need to correct that tomorrow.~

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

**Review by rosecodym — APPROVED** [review]
thanks for this!

**Comment by dustin-decker** [comment]
I think this is okay because we own the service being checked, but otherwise we should not do this for other providers. If anything, we need to consider host-based throttling to ensure we're not slamming providers.

**Comment by rgmz** [comment]
That is correct, and it will still iterate through each result sequentially as the WaitGroup is inside the loop.

I suppose you could argue that if the detector is faster it will lead to more requests, however, I don't forsee that being a meaningful increase.

**Comment by rgmz** [comment]
I've resolved the conflicts.

**Pull request merged**
