### PR TITLE
Adding the capability for scanning a directory

### PR DESCRIPTION
**Pull request by runako**
This PR adds the capability for truffleHog to recursively scan a directory instead of a Git repository with all its history. This can be useful in CI pipelines or other situations where it is desirable to scan the codebase at a single point in time. Additionally, it can also be used to scan code that is not stored in Git.

I've done some minor refactoring to the existing scanning code to reduce code duplication.

### CODE REVIEW

**Comment by ddnomad** [comment]
Wonder why this is still not merged :| 

Would make multi-tool wrappers implementation so much better. Right now I'm cloning a repo and scan it with multiple tools and all except for truffleHog assume I've scanned a repo myself. Have to let truffleHog clone again to be able to use it as is (without forking) which is a total pita.

**Comment by anshumanbh** [comment]
@ddnomad Have you considered https://github.com/anshumanbh/git-all-secrets?

**Comment by dxa4481** [comment]
Sorry, been busy with a defcon talk and other life stuff, I'll carve out some time to go through the PR backlog soon

**Comment by jliviero** [comment]
Any movement on this?  Would love to see this functionality.

**Comment by nabster11** [comment]
Hey @dxa4481 could you review this PR, I have a use-case where directory scanning is involved and not a git repo.

If you need to any help, I would love to take this up.

**Comment by BBerastegui** [comment]
Bump on this. 🎉 

@dxa4481

**Comment by kiwiz** [comment]
I've also a use for this functionality & I'm willing to put effort to get this work.

**Comment by lberezy** [comment]
Hate to bump this but any updates?

**Comment by kiwiz** [comment]
Fwiw, I've been using this fork: https://github.com/feeltheajf/truffleHog3

**Comment by derBroBro** [comment]
@dxa4481 need this as well. :)

**Comment by moivica** [comment]
Any news? Really nice feature to have...

**Comment by dustin-decker** [comment]
Hey there, we've just released the next major version of TruffleHog! 

It includes filesystem scanning!

It is a complete rewrite that scans more data sources and now supports detecting and verifying over 600 credentials.
Please check it out when you can.

https://trufflesecurity.com/blog/introducing-trufflehog-v3

We're no longer maintaining v2 so I am closing this PR.

**Pull request closed without merging**
