### PR TITLE
Update SumoLogic detector

### PR DESCRIPTION
**Pull request by rgmz**
### Description:
This makes a number of fixes and improvements to the SumoLogic detector.

- Use tri-state verification
- Update keywords
- Improve id pattern
- Deduplicate matches
- Add URL pattern to detect region-specific API endpoints
- Adds unit tests

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

**Review by abmussani — COMMENTED** [review]
Thank you @rgmz for the fixes. Your changes includes regarding the custom endpoints but tests does not include that. Can you modify unit test to cover them as well ?

**Comment by rgmz** [comment]
> Your changes includes implementation of the custom endpoints but tests does not include that. Can you modify unit test to cover them as well ?

@abmussani Done!

**Review by ahrav — APPROVED** [review]
Just a single non-blocking question, otherwise looks awesome. Thanks!

**Comment by rgmz** [comment]
> Just a single non-blocking question

Did you forget to leave it? Or are you referring to the existing one?

**Comment by ahrav** [comment]
> > Just a single non-blocking question
> 
> Did you forget to leave it? Or are you referring to the existing one?

errr.. lol, I guess I forgot to leave it 🤣 It wasn't really important.

**Pull request merged**
