### PR TITLE
[chore] add figmav2 to defaults

### PR DESCRIPTION
**Pull request by 0x1**
### Description:
add figmav2 to defaults

### Checklist:
* [ ] Tests passing (`make test-community`)?
* [ ] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

**Review by mcastorina — COMMENTED** [review]
`figmapersonalaccesstokenV2` should be replaced with `figmapersonalaccesstoken_v2` since the package name should match the directory it's in. Typically Go uses underscores for packages instead of camel case since some filesystems are case insensitive (my theory).

**Comment by 0x1** [comment]
> `figmapersonalaccesstokenV2` should be replaced with `figmapersonalaccesstoken_v2` since the package name should match the directory it's in. Typically Go uses underscores for packages instead of camel case since some filesystems are case insensitive (my theory).

agreed w/ package name should match directory name. but the [docs](https://go.dev/blog/package-names#Package-names:~:text=They%20are%20lower%20case%2C%20with%20no%20under_scores%20or%20mixedCaps.) say package names should be lowercase and no mixedCaps or underscores. thoughts?

**Comment by 0x1** [comment]
> > `figmapersonalaccesstokenV2` should be replaced with `figmapersonalaccesstoken_v2` since the package name should match the directory it's in. Typically Go uses underscores for packages instead of camel case since some filesystems are case insensitive (my theory).
> 
> agreed w/ package name should match directory name. but the [docs](https://go.dev/blog/package-names#Package-names:~:text=They%20are%20lower%20case%2C%20with%20no%20under_scores%20or%20mixedCaps.) say package names should be lowercase and no mixedCaps or underscores. thoughts?

apparently the [right way](https://go.dev/blog/v2-go-modules) to do this is by adding the version to the import path, but keeping the original package name. it's actually pretty clean.

**Review by ahrav — APPROVED** [review]
very nice!

**Review by mcastorina — APPROVED** [review]

**Pull request merged**
