### PR TITLE
readme improvements

### PR DESCRIPTION
**Pull request by dustin-decker**
Preview: https://github.com/trufflesecurity/trufflehog/blob/readme-improvements/README.md

### CODE REVIEW

**Comment by mcastorina** [comment]
Github also has a [rich text diff view](https://github.com/trufflesecurity/trufflehog/pull/1234/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) which makes it easier to visualize the changes.

**Review by mcastorina — APPROVED** [review]
Nice!

**Comment by zricethezav** [comment]
Looks great

**Comment by dustin-decker** [comment]
> Github also has a [rich diff view](https://github.com/trufflesecurity/trufflehog/pull/1234/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) which makes it easier to visualize the changes.

I didn't know about that!

I just added a few more changes (headings and order changes, mostly)

**Pull request merged**
