### PR TITLE
Use forked sevenzip

### PR DESCRIPTION
**Pull request by bill-rich**
Standard sevenzip doesn't check that digest[j] exists and can cause a panic

### CODE REVIEW

**Review by mcastorina — APPROVED** [review]
Is this until [your PR](https://github.com/bodgit/sevenzip/pull/135) gets merged?

**Comment by bill-rich** [comment]
> Is this until [your PR](https://github.com/bodgit/sevenzip/pull/135) gets merged?

Also to test that this fix works since we don't have access to the archive causing it.

**Comment by dustin-decker** [comment]
I've hit a panic in this library while scanning the chromium repo:

```Found unverified result 🐷🔑❓
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x21b43c2]

goroutine 2905408 [running]:
github.com/bodgit/sevenzip.readHeader({0x3c0d018, 0xc004000f00})
        /home/runner/go/pkg/mod/github.com/bill-rich/sevenzip@v0.0.0-20231205215127-9521c543efac/types.go:837 +0x2c2
github.com/bodgit/sevenzip.(*Reader).init(0xc004bd7050, {0x7faff4f33470?, 0xc005ca0660}, 0x6d)
        /home/runner/go/pkg/mod/github.com/bill-rich/sevenzip@v0.0.0-20231205215127-9521c543efac/reader.go:379 +0x7d3
github.com/bodgit/sevenzip.NewReaderWithPassword({0x7faff4f33470, 0xc005ca0660}, 0x6d, {0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/bill-rich/sevenzip@v0.0.0-20231205215127-9521c543efac/reader.go:242 +0x93
github.com/mholt/archiver/v4.SevenZip.Extract({0x0?, {0x0?, 0x0?}}, {0x7faff518cda8, 0xc005ca0cc0}, {0x3bf4da0?, 0xc005ca0660?}, {0x0, 0x0, 0x0}, ...)
        /home/runner/go/pkg/mod/github.com/mholt/archiver/v4@v4.0.0-alpha.8/7z.go:76 +0x12b
github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).openArchive(0xc002ec2f00, {0x3c2d300, 0xc005ca09f0}, 0x0, {0x3bf4da0, 0xc005ca0660}, 0xc004000ea0)
        /home/runner/work/trufflehog/trufflehog/pkg/handlers/archive.go:115 +0x2e3
github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).FromFile.func1()
        /home/runner/work/trufflehog/trufflehog/pkg/handlers/archive.go:76 +0x1da
created by github.com/trufflesecurity/trufflehog/v3/pkg/handlers.(*Archive).FromFile in goroutine 219
        /home/runner/work/trufflehog/trufflehog/pkg/handlers/archive.go:71 +0xe5

**Comment by rgmz** [comment]
@dustin-decker This _should_ be fixed in the latest version (v1.4.5). I've opened #2215 to upgrade to that.

**Pull request merged**
