### PR TITLE
Fix wrong line number

### PR DESCRIPTION
**Pull request by shreyas-sriram**
### Description:
This fixes the wrong line numbers that are reported. See https://github.com/trufflesecurity/trufflehog/issues/1876.

- line number is to be calculated as `count("\n") + 1`

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/usage/install/#local-installation))?

### CODE REVIEW

**Comment by shreyas-sriram** [comment]
Hey @dustin-decker! Can I get a review of this?

**Review by bill-rich — APPROVED** [review]
Thanks for the fix!

**Comment by sxlijin** [comment]
This doesn't appear to be a "fix wrong line number" PR - this changes trufflehog's JSON output from returning 0-indexed line numbers to 1-indexed line numbers and **is a backwards breaking change**.

**Comment by bill-rich** [comment]
Turns out that the issue is only in the `filesystem` source. The fix is to add line-aware chunking there.

**Pull request merged**
