### PR TITLE
feat: validation & verification fix for `apiscience` to `apimetrics`

### PR DESCRIPTION
**Pull request by sahil9001**
### Description:

- Moved `apiscience` to `apimetrics` module.
- Updated the verification logic for token.
- Updated the API endpoint for verification.
Screenshot 2024-10-19 at 2 38 57 AM

### Checklist:
* [x] Tests passing (`make test-community`)?
* [x] Lint passing (`make lint` this requires [golangci-lint](https://golangci-lint.run/welcome/install/#local-installation))?

### CODE REVIEW

**Comment by sahil9001** [comment]
Hey @kashifkhan0771 , can you please check this, I have a lot of PRs open with no reviews

**Comment by kashifkhan0771** [comment]
I reviewed couple of your PR's. Once those are merged/closed - will review further. Thank you for all the contribution @sahil9001.

**Review by kashifkhan0771 — APPROVED** [review]
LGTM!

**Comment by sahil9001** [comment]
Can you add the label here too @kashifkhan0771 ?

**Review by zricethezav — APPROVED** [review]

**Pull request merged**
