### PR TITLE
Build and Publish Homebrew Package

### PR DESCRIPTION
**Pull request by drewstinnett**
This will add a homebrew targets in, using the existing goreleaser process. This PR should address #186 

Note that I've got my personal repo in there now as a target (mainly so I could test that it actually works). These should be changed to whatever you folks think is appropriate 😁

### CODE REVIEW

**Comment by dustin-decker** [comment]
Thanks a lot, Drew! Looking forward to getting this released

**Comment by drewstinnett** [comment]
Happy to help however I can!

**Comment by dustin-decker** [comment]
Do you know if there is any downside to having the brew formulas in this repository?

**Comment by drewstinnett** [comment]
I don't think it can go directly in this repository...in order for the tap names to work, the repository name needs to be prefixed with `homebrew-`. So for example, it would need to go into a repository like:

`github.com/trufflesecurity/homebrew-trufflehog`

Then it could be tapped with: `brew tap trufflesecurity/trufflehog` (Note how the `homebrew-` is dropped from the tap cli)

What some folks do, is create a tap to hold all their formulas, which may be good here if there are other homebrew packages you wanna put up. In this case, you could have something like `trufflesecurity/homebrew-tap`, which would work with `brew tap trufflesecurity/tap`

Full docs on this is [here](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap), if it's helpful!

**Comment by dustin-decker** [comment]
Thanks a lot, Drew. I've setup the new repository and a service account token in the secrets for this repo. I've also renamed the owner in your PR. I think it's ready to go 🚀

**Review by dustin-decker — APPROVED** [review]

**Comment by drewstinnett** [comment]
Looks awesome Dustin! Feel free to ping me if anything is wonky and thanks!!

**Pull request merged**
