### PR TITLE
errors from client.Do(req) are ignored - leading to potential false negatives

### PR DESCRIPTION
**Pull request by ManQuiche**
Hello guys, I'm sorry I won't have time to work on this the next few weeks... But here is my work.

### CODE REVIEW

**Comment by dustin-decker** [comment]
Much appreciated, @ManQuiche. We'll take it from here.

**Comment by ManQuiche** [comment]
Hi, you're welcome. It's issue #1198

**Comment by dustin-decker** [comment]
We really appreciate your effort on this. Unfortunately after talking about the problem more internally, we took a different approach which mostly involved storing verification error inside the result. I apologize for prematurely selecting a solution with you. We have already updated some of the most impacted detectors with this approach, and will be doing bulk refactoring of the remaining over the time: 

https://github.com/search?q=repo%3Atrufflesecurity%2Ftrufflehog+tri-state&type=pullrequests

I'll close this draft because of the solution that is being implemented now.

**Comment by ManQuiche** [comment]
No problem, this is a better solution !

**Pull request closed without merging**
